#!/bin/bash

./gradlew spotlessApply --daemon --parallel -q

if [ $? -ne 0 ]; then
    echo "spotless formatting error"
    exit 1
fi

# update in git stage only  commited files
git diff --cached --name-only --diff-filter=ACM | while read FILE; do
  if [ -f "$FILE" ]; then
    git add "$FILE"
  fi
done

echo "[OK] code formatted"
