name: noisif

services:
  noisif-rabbitmq:
    container_name: noisif-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '${NS_RABBITMQ_AMQP_PORT:-5672}:5672'
      - '${NS_RABBITMQ_PANEL_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "noisif-main"
    volumes:
      - ./.volumes/rabbitmq/rabbitmq-volume:/var/lib/rabbitmq
    networks:
      - noisif-network

  noisif-redis:
    container_name: noisif-redis
    image: redis:7.2-alpine
    ports:
      - "${NS_REDIS_SINGLE_NODE_PORT:-6379}:6379"
    volumes:
      - ./.volumes/redis/redis-volume:/data
    networks:
      - noisif-network

  noisif-redis-ui:
    container_name: noisif-redis-ui
    image: rediscommander/redis-commander:latest
    ports:
      - "${NS_REDIS_PANEL_PORT:-8081}:8081"
    environment:
      REDIS_HOSTS: local:noisif-redis:6379
    depends_on:
      - noisif-redis
    networks:
      - noisif-network

  noisif-postgres:
    container_name: noisif-postgres
    image: postgres:16-alpine
    ports:
      - "${NS_POSTGRES_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    volumes:
      - ./.volumes/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.volumes/postgres/postgres-volume:/var/lib/postgresql/data
    networks:
      - noisif-network

  noisif-postgres-ui:
    container_name: noisif-postgres-ui
    build:
      context: ./.volumes/pgadmin
    pull_policy: build
    ports:
      - "${NS_POSTGRES_PANEL_PORT:-8082}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@noisif.xyz"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    entrypoint: /usr/local/bin/entrypoint-wrapper
    volumes:
      - ./.volumes/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./.volumes/pgadmin/pgpassfile:/tmp/mountpoint.pgpass
    depends_on:
      - noisif-postgres
    networks:
      - noisif-network

  noisif-neo4j:
    container_name: noisif-neo4j
    image: neo4j:5.12.0
    ports:
      - "${NS_NEO4J_PANEL_PORT:-7474}:7474"
      - "${NS_NEO4J_DB_PORT:-7687}:7687"
    volumes:
      - ./.volumes/neo4j/neo4j-volume/data:/data
      - ./.volumes/neo4j/neo4j-volume/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/root
      NEO4J_initial_dbms_default__database: ns-oss
      NEO4J_dbms_security_auth__minimum__password__length: 3
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_memory_pagecache_size: 512m
    networks:
      - noisif-network

networks:
  noisif-network:
    driver: bridge
